image: ros:kinetic-robot

before_script:
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null


catkin_build:
  stage: build
  script:
    - catkin build
